version: '3.2'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - node

  node:
    build: .
    volumes: 
      - ./src:/src
    links:
      - mongodb

  mongodb:
    image: mongodb:latest
    ports:
      - "27018:27017"
