version: '3.2'
services:
  node:
    build: .
    volumes: 
      - ./src:/src
    links:
      - mongodb
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: curl -f http://localhost:3000/-/healthz || exit 1
      interval: 10s
      timeout: 5s
      retries: 2

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
