version: '3.2'
services:
  node:
    build: .
    volumes: 
      - ./src:/src
    links:
      - mongodb
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
