version: '3.4'
services:
  node:
    build: .
    volumes: 
      - ./src:/src
    links:
      - mongodb
    ports:
      - "3000:3000"
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
