version: '3.4'
services:
  node:
    build: .
    volumes: 
      - ./src:/src
    links:
      - mongodb
    ports:
      - "3000:3000"
    restart: always

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
